---
- name: Handlers in ansible
  hosts: all
  become: yes
  vars: 
    app: apache2
  tasks: 
    - name: installing apache 2
      ansible.builtin.apt:
        name: "{{ app }}"
        state: present
      notify:
        - restart apache2  
  handlers:
    - name: restart apache2
      ansible.builtin.systemd:
        name: "{{ app }}"
        state: restarted
