---
- name: installing nginx and using handlers to start nginx
  hosts: all
  become: yes
  vars:
    app: nginx
  tasks:
    - name: installing nginx
      ansible.builtin.package:
        name: nginx
        state: present
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      ansible.builtin.systemd:
        name: "{{ app }}"
        state: restarted