---
- name: installing dotnet 7 on centos 7
  hosts: all
  become: yes
  vars:
    link: https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm
    os_ver: 22.04
    deb_microsoft_key: "https://packages.microsoft.com/config/ubuntu/{{ os_ver }}/packages-microsoft-prod.deb"
    deb_package: packages-microsoft-prod.deb
    sdk_ver: 7.0
    install_sdk: "dotnet-sdk-{{ sdk_ver }}"
    install_https_cert: apt-transport-https
    runtime_ver: 7.0
    install_runtime: "aspnetcore-runtime-{{ runtime_ver }}"
  tasks:
    - name: update cache
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_facts['distribution'] == "CentOS"
    - name: downloading deb-microsoft-key
      ansible.builtin.get_url:
        url: "{{ link }}" 
        dest: .
        mode: "777"
      when: ansible_facts['distribution'] == "CentOS"
    - name: 
      ansible.builtin.yum:
        name: 
          - ./packages-microsoft-prod.rpm
          - dotnet-sdk-7.0
          - aspnetcore-runtime-7.0
        state: present
      when: ansible_facts['distribution'] == "CentOS"

    - name: downloading deb-microsoft-key
      ansible.builtin.get_url:
        url: "{{ deb_microsoft_key }}" 
        dest: .
        mode: "777"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: Install a .deb package
      ansible.builtin.apt:
        deb: ./packages-microsoft-prod.deb 
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: installing dotnet sdk
      ansible.builtin.package:
        name:
          - "{{ install_https_cert }}"
          - "{{ install_sdk }}"
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: installing netcore runtime
      ansible.builtin.package:
        name: 
          - "{{ install_https_cert }}"
          - "{{ install_runtime }}"
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

# Additionally you can check with a simple HELLOWORLD application, the steps are
# dotnet new console -o HelloWorld
# cd  HelloWorld
# dotnet run


  




