---
- name: variables demo
  hosts: ubuntu
  become: yes
  tasks:
    - name: print variables demo
      ansible.builtin.debug:
        var: name
    - name: print something
      ansible.builtin.debug:
        msg: "Assalamualaikum {{ name }} bhai"